[package]
name = "w65c02s"
version = "0.9.0"
authors = ["Solra Bizna <solra@bizna.name>"]
edition = "2018"
description = "Cycle-accurate, exhaustively tested simulator of W65C02S microprocessor"
license = "Zlib"
repository = "https://github.com/SolraBizna/rust-w65c02s"

[dependencies]
